# Generated by Django 5.0 on 2023-12-11 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('db_id', models.AutoField(primary_key=True, serialize=False)),
                ('db_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('db_id', models.AutoField(primary_key=True, serialize=False)),
                ('db_title', models.CharField(max_length=255)),
                ('db_description', models.TextField()),
                ('db_publish', models.DateField(auto_now=True)),
                ('db_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.category')),
            ],
        ),
    ]
