# Generated by Django 5.0 on 2023-12-13 19:06

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='db_thumbnail',
            field=models.ImageField(default=1, upload_to='category_thumbnails/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='db_thumbnail',
            field=models.ImageField(default=1, storage=django.core.files.storage.FileSystemStorage(location='/media/'), upload_to='post_thumbnails/'),
            preserve_default=False,
        ),
    ]
